# fly.toml app configuration file generated for nzpmc-mini-project on 2023-12-31T19:16:20+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nzpmc-mini-project"
primary_region = "syd"

[build]

[env]
  PORT = "3000"
  MODE = "PROD"
  DB_URL = "mongodb+srv://Just:<password>@oculux.voxjd1o.mongodb.net/nzpmc-mini-project?retryWrites=true&w=majority"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
